name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Pull in dev.to posts
          uses: gautamkrishnar/blog-post-workflow@v1
          with:
            feed_list: "https://jhilker.com/blog/feed.xml"